using FrameHub.Core.Models;
using FrameHub.Core.Services;

namespace FrameHub.App.Services;

public sealed class LocalizationService
{
    private readonly SettingsService _settingsService;
    private AppSettings _settings;

    public event EventHandler? LanguageChanged;

    public string CurrentLanguage => _settings.Language;

    public LocalizationService(SettingsService settingsService)
    {
        _settingsService = settingsService;
        _settings = _settingsService.Load();
    }

    public void SetLanguage(string languageCode)
    {
        string normalized = NormalizeLanguage(languageCode);
        if (_settings.Language == normalized)
        {
            return;
        }

        _settings.Language = normalized;
        _settingsService.Save(_settings);
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string T(string key)
    {
        var dictionary = CurrentLanguage == "pl" ? Polish : English;

        if (dictionary.TryGetValue(key, out string? value))
        {
            return value;
        }

        return English.TryGetValue(key, out string? fallback) ? fallback : key;
    }

    private static string NormalizeLanguage(string languageCode)
    {
        return languageCode.Equals("pl", StringComparison.OrdinalIgnoreCase) ? "pl" : "en";
    }

    private static readonly Dictionary<string, string> English = new(StringComparer.OrdinalIgnoreCase)
    {
        ["App.Tagline"] = "Open Windows performance hub for games and apps",
        ["Language.Label"] = "Language",
        ["Language.English"] = "English",
        ["Language.Polish"] = "Polski",
        ["Status.CoreFoundation"] = "Core foundation",
        ["Status.WatcherFoundationReady"] = "Watcher ready",
        ["Status.CoreMigrated"] = "Core module active",
        ["Status.WatcherActive"] = "Watcher active",
        ["Status.WatcherInactive"] = "Watcher inactive",

        ["Nav.Dashboard"] = "Dashboard",
        ["Nav.Library"] = "Library",
        ["Nav.Session"] = "Session Optimizer",
        ["Nav.CoreControl"] = "Core Control",
        ["Nav.ProfilesRules"] = "Profiles & Rules",
        ["Nav.Background"] = "Background Control",
        ["Nav.Toolkit"] = "System Toolkit",
        ["Nav.Hardware"] = "Hardware",
        ["Nav.Benchmark"] = "Benchmarks",
        ["Nav.WindowsTuning"] = "Windows Tuning",
        ["Nav.Settings"] = "Settings",
        ["Nav.Logs"] = "Logs",
        ["Nav.Games"] = "Games",
        ["Nav.Boost"] = "Boost",
        ["Nav.Processes"] = "Processes",
        ["Nav.Profiles"] = "Profiles",
        ["Nav.Tweaks"] = "Tweaks",
        ["Nav.Debloat"] = "Windows 11 Debloat",

        ["Badge.Soon"] = "SOON",
        ["Badge.Safe"] = "SAFE",
        ["Badge.Planned"] = "PLANNED",
        ["Badge.Preview"] = "PREVIEW",
        ["Badge.Ready"] = "READY",

        ["Dashboard.Title"] = "Dashboard",
        ["Dashboard.Subtitle"] = "FrameHub product shell, active core status and next modules.",
        ["Metric.BackgroundWatcher.Title"] = "Background Watcher",
        ["Metric.BackgroundWatcher.Value"] = "Reserved",
        ["Metric.BackgroundWatcher.ValueActive"] = "Active",
        ["Metric.BackgroundWatcher.ValueOff"] = "Off",
        ["Metric.BackgroundWatcher.Detail"] = "{0} enabled profile(s)",
        ["Metric.OptimizedApps.Title"] = "Optimized Apps",
        ["Metric.OptimizedApps.Value"] = "0",
        ["Metric.OptimizedApps.Detail"] = "No active session yet",
        ["Metric.HardwareMonitor.Title"] = "Hardware Monitor",
        ["Metric.HardwareMonitor.Value"] = "Off",
        ["Metric.HardwareMonitor.Detail"] = "Manual telemetry module",
        ["Metric.Debloat.Title"] = "Windows Tuning",
        ["Metric.Debloat.Value"] = "Preview",
        ["Metric.Debloat.Detail"] = "No system changes yet",
        ["Dashboard.FoundationPlan.Title"] = "Product map",
        ["Dashboard.FoundationPlan.Description"] = "FrameHub is an open-source performance hub prepared for gaming sessions, app rules, system tools and safe Windows tuning. Planned modules will be added gradually with clear descriptions and rollback where needed.",
        ["Dashboard.Target.Title"] = "Current foundation",
        ["Dashboard.Target.Description"] = "Core Control is already connected: process profiles, CPU Sets, affinity, priority, logging and background profile watcher.",
        ["Dashboard.Migration.Title"] = "Next modules",
        ["Dashboard.Migration.Description"] = "Library, Session Optimizer, Background Control, System Toolkit, Benchmarks and Windows Tuning are mapped in the UI and will be implemented step by step.",
        ["Dashboard.RecentActivity.Title"] = "Recent activity",
        ["Activity.ShellInitialized"] = "FrameHub product shell initialized.",
        ["Activity.WatcherReserved"] = "Background profile watcher is active and independent from the UI.",
        ["Activity.HardwareDisabled"] = "Hardware monitor is disabled until explicitly enabled.",
        ["Activity.DebloatPlanned"] = "Windows Tuning is preview-only. No debloat actions are enabled.",

        ["Placeholder.CurrentState.Title"] = "Current state",
        ["Placeholder.CurrentState.Description"] = "This module is already placed in the product navigation. Features will be attached in safe, testable stages instead of adding risky system changes all at once.",
        ["Placeholder.PlannedCapabilities.Title"] = "Planned capabilities",
        ["Placeholder.SafetyRule.Title"] = "FrameHub safety rule",
        ["Placeholder.SafetyRule.Description"] = "No game memory editing, no DLL injection, no kernel drivers, no anti-cheat bypass wording and no hidden destructive tweaks. Every global change must be transparent, reversible and logged.",


        ["Library.Title"] = "Library",
        ["Library.Subtitle"] = "Detected and manually added games, apps and background tools.",
        ["Library.ScanTitle"] = "Scan game libraries",
        ["Library.ManualTitle"] = "Add manually",
        ["Library.ItemsTitle"] = "Library items",
        ["Library.CustomFoldersTitle"] = "Custom library locations",
        ["Library.Empty"] = "Scan Steam/Epic, add a custom folder or add an executable manually.",
        ["Library.DisplayName"] = "Display name",
        ["Library.Executable"] = "Executable path",
        ["Library.Type"] = "Type",
        ["Library.Browse"] = "Browse",
        ["Library.AddManual"] = "Add item",
        ["Library.ScanSteam"] = "Scan Steam",
        ["Library.ScanEpic"] = "Scan Epic",
        ["Library.ScanAll"] = "Scan all",
        ["Library.AddFolder"] = "Add folder",
        ["Library.ScanCustom"] = "Scan custom folders",
        ["Library.RefreshStatus"] = "Refresh status",
        ["Library.SafetyTitle"] = "Safe detection only",
        ["Library.SafetyDescription"] = "Library scans only read launcher manifests and selected folders. It does not modify games, inject files, read game memory or touch anti-cheat processes.",
        ["Library.Remove"] = "Remove",
        ["Library.Ready"] = "Library ready.",
        ["Library.ReadyCount"] = "{0}/{1} ready",
        ["Library.NotConfigured"] = "Not configured",
        ["Library.ExeMissing"] = "Executable not selected",
        ["Library.WatcherOn"] = "Watcher enabled",
        ["Library.WatcherOff"] = "Watcher disabled",
        ["Library.ProfileLinked"] = "Profile linked",
        ["Library.ProfileMissing"] = "Profile missing",
        ["Library.Status.Optimized"] = "Running + profiled",
        ["Library.Status.Running"] = "Running",
        ["Library.Status.NotRunning"] = "Not running",
        ["Library.Status.Ready"] = "Ready",
        ["Library.Status.NeedsSetup"] = "Needs setup",
        ["Library.ExecutableMissing"] = "Select an existing .exe file first.",
        ["Library.ManualAdded"] = "Manual item added.",
        ["Library.ScanResult"] = "Detected {0} item(s).",
        ["Library.SourceScanResult"] = "{0} scan detected {1} item(s).",
        ["Library.FolderAdded"] = "Folder added: {0}",
        ["Library.ItemRemoved"] = "Removed: {0}",
        ["Library.Type.Game"] = "Game",
        ["Library.Type.App"] = "App",
        ["Library.Type.BackgroundApp"] = "Background app",
        ["Library.Type.Launcher"] = "Launcher",
        ["Library.DetailsTitle"] = "Selected item",
        ["Library.NoSelection"] = "Select a Library item to manage profiles or game settings.",
        ["Library.Launch"] = "Launch",
        ["Library.OpenFolder"] = "Open folder",
        ["Library.ProfileEditorTitle"] = "Optimization profile",
        ["Library.ProfileEditorHint"] = "Choose a mode, priority and exact CPU assignment for this game/app.",
        ["Library.CpuCores"] = "Physical cores",
        ["Library.CpuThreads"] = "SMT / HT threads",
        ["Library.CreateUpdateProfile"] = "Create / update profile",
        ["Library.ApplyProfileNow"] = "Apply profile now",
        ["Library.ProfileSaved"] = "Optimization profile saved for {0}.",
        ["Library.ProfileApplied"] = "Applied profile for {0}.",
        ["CS2.Title"] = "Counter-Strike 2 optimizer",
        ["CS2.Subtitle"] = "Analyze CS2 settings, link a CPU profile and apply safe config presets with backup first.",
        ["CS2.Scan"] = "Scan CS2 settings",
        ["CS2.Backup"] = "Create backup",
        ["CS2.ApplyPreset"] = "Create backup + apply selected",
        ["CS2.RestoreLatest"] = "Show latest backup",
        ["CS2.CurrentSettings"] = "CS2 settings editor",
        ["CS2.Preset"] = "Preset",
        ["CS2.NotScanned"] = "Select Counter-Strike 2 and scan settings.",
        ["CS2.NotDetected"] = "CS2 video config not detected yet.",

        ["CS2.OverviewTitle"] = "Detected CS2 setup",
        ["CS2.Card.Resolution"] = "Resolution",
        ["CS2.Card.DisplayMode"] = "Display mode",
        ["CS2.Card.VSync"] = "Vertical Sync",
        ["CS2.Card.Baseline"] = "Baseline match",
        ["CS2.ConfigPath"] = "Config file",
        ["CS2.NotScannedShort"] = "Not scanned",
        ["CS2.BaselineMatch"] = "{0}/{1} matching",
        ["CS2.PresetDescriptionFallback"] = "Choose a preset to compare your current CS2 settings against the FrameHub baseline.",
        ["CS2.Preset.cs2_latest_backup.Description"] = "Values loaded from the latest FrameHub CS2 backup. Use this to compare or restore individual settings.",
        ["CS2.Preset.cs2_current_backup_placeholder.Description"] = "No previous FrameHub CS2 backup was found. This preset mirrors the currently detected config.",
        ["CS2.Preset.cs2_competitive_baseline.Description"] = "FrameHub competitive baseline based on your supplied CS2 settings. It keeps the same competitive values and changes only display mode to true fullscreen.",
        ["CS2.Table.Apply"] = "Apply",
        ["CS2.Table.Setting"] = "Setting",
        ["CS2.Table.Current"] = "Current",
        ["CS2.Table.Recommended"] = "Recommended",
        ["CS2.Table.SetTo"] = "Set",
        ["CS2.Table.Status"] = "Status",
        ["CS2.ApplyThisSetting"] = "Apply this setting",
        ["CS2.ReadOnlySetting"] = "Read-only / informational",
        ["CS2.SafetyTitle"] = "FrameHub CS2 safety model",
        ["CS2.SafetyDescription"] = "FrameHub reads CS2 config files, creates backups and applies selected text config changes only. Close CS2 before applying changes, otherwise the game may overwrite the config on exit.",
        ["CS2.SettingsListTitle"] = "Editable CS2 video settings",
        ["CS2.SettingsListHint"] = "Each option is shown as a clear game setting. Pick a value from the dropdown and tick only the changes you want to apply.",
        ["CS2.Autoexec.Title"] = "CS2 autoexec.cfg editor",
        ["CS2.Autoexec.Subtitle"] = "Edit or create autoexec.cfg directly from FrameHub. Use safe snippets for grenade binds, radar and fps_max, then save the file.",
        ["CS2.Autoexec.Path"] = "autoexec.cfg path",
        ["CS2.Autoexec.NotDetected"] = "CS2 game cfg folder not detected.",
        ["CS2.Autoexec.OpenCreate"] = "Open / create autoexec",
        ["CS2.Autoexec.Save"] = "Save autoexec.cfg",
        ["CS2.Autoexec.OpenFolder"] = "Open cfg folder",
        ["CS2.Autoexec.AddGrenades"] = "Add grenade binds",
        ["CS2.Autoexec.AddRadar"] = "Add large radar",
        ["CS2.Autoexec.AddFps"] = "Add fps_max",
        ["CS2.Autoexec.FpsLabel"] = "FPS max",
        ["CS2.Autoexec.SnippetAdded"] = "Snippet inserted into autoexec editor. Save the file to apply it.",
        ["CS2.Status.MatchesBaseline"] = "Matches baseline",
        ["CS2.Status.DifferentFromBaseline"] = "Different",
        ["CS2.Status.OptionalPreference"] = "Optional / preference",
        ["CS2.Status.NotDetected"] = "Not detected",
        ["CS2.Status.ReadOnly"] = "Info only",
        ["CS2.Value.NotDetected"] = "Not detected automatically",
        ["CS2.Value.On"] = "Enabled",
        ["CS2.Value.Off"] = "Disabled",
        ["CS2.Value.Enabled"] = "Enabled",
        ["CS2.Value.Disabled"] = "Disabled",
        ["CS2.Value.Display.fullscreen"] = "Fullscreen",
        ["CS2.Value.Display.borderless"] = "Borderless fullscreen",
        ["CS2.Value.Display.windowed"] = "Windowed",
        ["CS2.Value.Display.not found"] = "Not detected",
        ["CS2.Value.MSAA.Mode.none"] = "None",
        ["CS2.Value.MSAA.Mode.cmaa2"] = "CMAA2",
        ["CS2.Value.MSAA.Mode.2x"] = "2X MSAA",
        ["CS2.Value.MSAA.Mode.4x"] = "4X MSAA",
        ["CS2.Value.MSAA.Mode.8x"] = "8X MSAA",
        ["CS2.Value.Quality.0"] = "Low",
        ["CS2.Value.Quality.1"] = "Medium",
        ["CS2.Value.Quality.2"] = "High",
        ["CS2.Value.Quality.3"] = "Very High",
        ["CS2.Value.DynamicShadows.0"] = "Sun only / limited",
        ["CS2.Value.DynamicShadows.1"] = "All",
        ["CS2.Value.TextureFiltering.0"] = "Bilinear",
        ["CS2.Value.TextureFiltering.1"] = "Trilinear",
        ["CS2.Value.TextureFiltering.2"] = "Anisotropic 2X",
        ["CS2.Value.TextureFiltering.3"] = "Anisotropic 4X",
        ["CS2.Value.TextureFiltering.4"] = "Anisotropic 8X",
        ["CS2.Value.TextureFiltering.5"] = "Anisotropic 16X",
        ["CS2.Value.HDR.-1"] = "Quality",
        ["CS2.Value.HDR.0"] = "Performance",
        ["CS2.Value.HDR.1"] = "Quality",
        ["CS2.Value.FSR.0"] = "Disabled (Highest Quality)",
        ["CS2.Value.FSR.1"] = "Quality",
        ["CS2.Value.FSR.2"] = "Balanced",
        ["CS2.Value.FSR.3"] = "Performance",
        ["CS2.Value.FSR.4"] = "Ultra Performance",
        ["CS2.Value.Resolution.1280x1024"] = "1280x1024 (5:4; CS2 shows 4:3)",
        ["CS2.Setting.cs2.resolution"] = "Resolution",
        ["CS2.Setting.cs2.display_mode"] = "Display Mode",
        ["CS2.Setting.r_player_visibility_mode"] = "Boost Player Contrast",
        ["CS2.Setting.setting.mat_vsync"] = "Vertical Sync",
        ["CS2.Setting.setting.r_low_latency"] = "AMD Anti-Lag 2.0 / Low Latency",
        ["CS2.Setting.cs2.msaa_mode"] = "Multisampling Anti-Aliasing Mode",
        ["CS2.Setting.setting.videocfg_shadow_quality"] = "Global Shadow Quality",
        ["CS2.Setting.setting.videocfg_dynamic_shadows"] = "Dynamic Shadows",
        ["CS2.Setting.setting.videocfg_texture_detail"] = "Model / Texture Detail",
        ["CS2.Setting.setting.r_texturefilteringquality"] = "Texture Filtering Mode",
        ["CS2.Setting.setting.shaderquality"] = "Shader Detail",
        ["CS2.Setting.setting.videocfg_particle_detail"] = "Particle Detail",
        ["CS2.Setting.setting.videocfg_ao_detail"] = "Ambient Occlusion",
        ["CS2.Setting.setting.videocfg_hdr_detail"] = "High Dynamic Range",
        ["CS2.Setting.setting.videocfg_fsr_detail"] = "FidelityFX Super Resolution",
        ["CS2.Description.cs2.resolution"] = "Common competitive resolutions. 1280x960 and 1440x1080 are 4:3 options.",
        ["CS2.Description.cs2.display_mode"] = "Fullscreen is the recommended performance mode; borderless is a comfort preference.",
        ["CS2.Description.r_player_visibility_mode"] = "Improves player contrast and visibility.",
        ["CS2.Description.setting.mat_vsync"] = "V-Sync should stay disabled for lower input latency.",
        ["CS2.Description.setting.r_low_latency"] = "Low-latency option exposed by CS2/driver integration.",
        ["CS2.Description.cs2.msaa_mode"] = "Anti-aliasing smooths edges but can reduce FPS.",
        ["CS2.Description.setting.videocfg_shadow_quality"] = "Lower shadow quality usually improves FPS.",
        ["CS2.Description.setting.videocfg_dynamic_shadows"] = "All dynamic shadows can help visibility; limited shadows may be faster.",
        ["CS2.Description.setting.videocfg_texture_detail"] = "Lower model and texture detail reduces visual load.",
        ["CS2.Description.setting.r_texturefilteringquality"] = "Texture filtering affects texture sharpness at angles.",
        ["CS2.Description.setting.shaderquality"] = "Lower shader detail reduces GPU overhead.",
        ["CS2.Description.setting.videocfg_particle_detail"] = "Lower particle detail can reduce effects overhead.",
        ["CS2.Description.setting.videocfg_ao_detail"] = "Ambient occlusion adds contact shadows and costs performance.",
        ["CS2.Description.setting.videocfg_hdr_detail"] = "HDR quality/performance preference.",
        ["CS2.Description.setting.videocfg_fsr_detail"] = "FSR upscaling can improve FPS but may reduce image clarity.",

        ["Module.Library.Title"] = "Library",
        ["Module.Library.Subtitle"] = "Games and app profiles in one place.",
        ["Module.Library.Status"] = "Planned for v0.2.0",
        ["Module.Library.Description"] = "The Library will replace manual process hunting with clean game/app cards. Users will be able to bind an executable path, icon, process names and a reusable optimization profile.",
        ["Module.Library.Item1"] = "Manual Add Game / Add App dialog",
        ["Module.Library.Item2"] = "Executable path binding instead of process-name only profiles",
        ["Module.Library.Item3"] = "Running / not running status per item",
        ["Module.Library.Item4"] = "Launcher scanners later: Steam, Epic, GOG, Battle.net, Riot, EA and Ubisoft",
        ["Module.Library.Item5"] = "Profile type: Game, App, Background App or Launcher",

        ["Module.Session.Title"] = "Session Optimizer",
        ["Module.Session.Subtitle"] = "Transparent one-click gaming sessions.",
        ["Module.Session.Status"] = "Planned for v0.3.0",
        ["Module.Session.Description"] = "Session Optimizer will not be a magic FPS button. It will show exactly which actions will run, whether they require admin rights and what will be restored after the game exits.",
        ["Module.Session.Item1"] = "Apply selected game/app profile",
        ["Module.Session.Item2"] = "Optional High Performance power plan during session",
        ["Module.Session.Item3"] = "Optional background app rules",
        ["Module.Session.Item4"] = "Session restore log for global changes",
        ["Module.Session.Item5"] = "Safe / Advanced / Experimental action labels",

        ["Module.Background.Title"] = "Background Control",
        ["Module.Background.Subtitle"] = "Rules for apps that keep running while you play.",
        ["Module.Background.Status"] = "Planned after Session Optimizer",
        ["Module.Background.Description"] = "This module will manage browsers, launchers, Discord, RGB tools and updaters without blindly killing system processes. The default behavior will be conservative and reversible.",
        ["Module.Background.Item1"] = "Lower priority for selected background apps",
        ["Module.Background.Item2"] = "Move selected apps to background CPU cores",
        ["Module.Background.Item3"] = "Memory Relief with clear warning and denylist",
        ["Module.Background.Item4"] = "Ask before closing selected apps",
        ["Module.Background.Item5"] = "Experimental suspend mode only with strong warnings",

        ["Module.Toolkit.Title"] = "System Toolkit",
        ["Module.Toolkit.Subtitle"] = "Small Windows tools, not risky magic tweaks.",
        ["Module.Toolkit.Status"] = "Planned utility module",
        ["Module.Toolkit.Description"] = "System Toolkit will hold safe everyday Windows utilities with previews, explanations and rollback where needed.",
        ["Module.Toolkit.Item1"] = "Safe Cleanup: TEMP, user TEMP, Recycle Bin and shader cache preview",
        ["Module.Toolkit.Item2"] = "Task Manager, Resource Monitor and Startup Apps shortcuts",
        ["Module.Toolkit.Item3"] = "Process Tools with critical process denylist",
        ["Module.Toolkit.Item4"] = "DNS presets: automatic, Cloudflare, Google, Quad9 and custom",
        ["Module.Toolkit.Item5"] = "Repair Tools: SFC, DISM, Flush DNS and Winsock reset",
        ["Module.Toolkit.Item6"] = "Restore point creation and classic Windows 11 context menu toggle",

        ["Module.Benchmark.Title"] = "Benchmarks",
        ["Module.Benchmark.Subtitle"] = "FPS, frametime and before/after reports.",
        ["Module.Benchmark.Status"] = "Planned after core workflows",
        ["Module.Benchmark.Description"] = "Benchmarking will make FrameHub measurable instead of placebo-driven. The target is a clean before/after workflow with CSV export and clear statistics.",
        ["Module.Benchmark.Item1"] = "Average FPS and frametime overview",
        ["Module.Benchmark.Item2"] = "1% low and 0.1% low tracking",
        ["Module.Benchmark.Item3"] = "Before / after optimization reports",
        ["Module.Benchmark.Item4"] = "Possible PresentMon-based capture later",

        ["Module.WindowsTuning.Title"] = "Windows Tuning",
        ["Module.WindowsTuning.Subtitle"] = "Preview-only safe Windows 11 tuning plan.",
        ["Module.WindowsTuning.Status"] = "Preview only",
        ["Module.WindowsTuning.Description"] = "This replaces the old idea of a one-click debloat. FrameHub will only expose Windows tuning with preview, restore point, backup and undo. It will not disable security services by default.",
        ["Module.WindowsTuning.Item1"] = "Preview changes before applying",
        ["Module.WindowsTuning.Item2"] = "Create restore point before risky actions",
        ["Module.WindowsTuning.Item3"] = "Registry backup and rollback plan",
        ["Module.WindowsTuning.Item4"] = "Privacy, background tasks, startup and Explorer UX groups",
        ["Module.WindowsTuning.Item5"] = "No Defender, Memory Integrity or anti-cheat disabling by default",

        ["Module.Settings.Title"] = "Settings",
        ["Module.Settings.Subtitle"] = "Application configuration.",
        ["Module.Settings.Status"] = "Foundation",
        ["Module.Settings.Description"] = "Settings will manage startup, tray behavior, theme, language, logs, update checks and safety defaults.",
        ["Module.Settings.Item1"] = "Start with Windows",
        ["Module.Settings.Item2"] = "Minimize / close to tray",
        ["Module.Settings.Item3"] = "Theme and language",
        ["Module.Settings.Item4"] = "Logging and diagnostics",
        ["Module.Settings.Item5"] = "Update checks and safety defaults",

        ["Module.Logs.Title"] = "Logs",
        ["Module.Logs.Subtitle"] = "Diagnostics and activity log.",
        ["Module.Logs.Status"] = "Ready",
        ["Module.Logs.Description"] = "Logs show watcher activity, applied profiles, failed actions and future session summaries.",
        ["Module.Logs.Item1"] = "Recent activity",
        ["Module.Logs.Item2"] = "Open log folder",
        ["Module.Logs.Item3"] = "Copy diagnostics later",
        ["Module.Logs.Item4"] = "Clear UI activity",


        ["Settings.Title"] = "Settings",
        ["Settings.Subtitle"] = "Startup, tray, language, logging, updates and safe defaults.",
        ["Settings.StartupTitle"] = "Startup",
        ["Settings.BehaviorTitle"] = "Window and tray behavior",
        ["Settings.LoggingTitle"] = "Logging and updates",
        ["Settings.SafetyTitle"] = "Safety and advanced options",
        ["Settings.DiagnosticsTitle"] = "Refresh intervals and diagnostics",
        ["Settings.LanguageTitle"] = "Application language",
        ["Settings.StartWithWindows"] = "Start with Windows",
        ["Settings.RunAsAdmin"] = "Start as Administrator",
        ["Settings.StartMinimized"] = "Start minimized",
        ["Settings.MinimizeToTray"] = "Minimize to tray",
        ["Settings.CloseToTray"] = "Close to tray",
        ["Settings.LogEnabled"] = "Enable file logging",
        ["Settings.CheckUpdates"] = "Check for updates at startup",
        ["Settings.AllowRealtime"] = "Show RealTime priority (advanced)",
        ["Settings.StorageSensors"] = "Enable storage sensors in Hardware Monitor",
        ["Settings.ProcessRefresh"] = "Process list refresh (seconds)",
        ["Settings.WatcherRefresh"] = "Background watcher interval (seconds)",
        ["Settings.HardwareRefresh"] = "Hardware refresh interval (seconds)",
        ["Settings.RestartAsAdminButton"] = "Restart as admin",
        ["Settings.CheckUpdatesButton"] = "Check now",
        ["Settings.OpenAppData"] = "Open AppData folder",
        ["Settings.OpenLogs"] = "Open logs folder",
        ["Settings.AdminYes"] = "Admin: yes",
        ["Settings.AdminNo"] = "Admin: no",
        ["Settings.Saved"] = "Settings saved",
        ["Settings.CheckingUpdates"] = "Checking for updates...",
        ["Settings.UpdateFailed"] = "Update check failed:",
        ["Settings.UpdateAvailable"] = "Update available: v{0}",
        ["Settings.OpenReleaseQuestion"] = "Open release page?",
        ["Settings.UpToDate"] = "FrameHub is up to date.",

        ["Processes.Title"] = "Core Control",
        ["Processes.Subtitle"] = "CPU Sets, affinity, priority and profile saving for running processes.",
        ["Processes.ListTitle"] = "Running processes",
        ["Processes.CoreSelectionTitle"] = "CPU core selection",
        ["Processes.SettingsTitle"] = "Optimization settings",
        ["Processes.SettingsSubtitle"] = "Select a process, choose cores and save a reusable profile.",
        ["Processes.Priority"] = "Priority",
        ["Processes.Mode"] = "Optimization mode",
        ["Processes.Apply"] = "Apply now",
        ["Processes.SaveProfile"] = "Save profile",
        ["Processes.SelectAll"] = "Select all",
        ["Processes.ClearAll"] = "Clear all",
        ["Processes.DisableSmt"] = "Disable SMT/HT",
        ["Processes.DisableECores"] = "Disable E-cores",
        ["Processes.Name"] = "Name",
        ["Processes.Instances"] = "Inst.",
        ["Processes.Ram"] = "RAM",
        ["Processes.Cpu"] = "CPU",
        ["Processes.NoSelection"] = "Select a process to configure optimization.",
        ["Processes.Selected"] = "Selected: {0}",

        ["Profiles.Title"] = "Profiles & Rules",
        ["Profiles.Subtitle"] = "Saved process rules watched in the background.",
        ["Profiles.SavedTitle"] = "Saved profiles",
        ["Profiles.DetailsTitle"] = "Profile details",
        ["Profiles.Apply"] = "Apply now",
        ["Profiles.Delete"] = "Delete",
        ["Profiles.Empty"] = "No profile selected.",
        ["Profiles.Name"] = "Name",
        ["Profiles.Mode"] = "Mode",
        ["Profiles.Priority"] = "Priority",
        ["Profiles.Enabled"] = "Enabled",

        ["Hardware.Title"] = "Hardware Monitor",
        ["Hardware.Subtitle"] = "Manual telemetry module. Sensors stay closed until enabled.",
        ["Hardware.Telemetry.Title"] = "Manual hardware telemetry",
        ["Hardware.Telemetry.Description"] = "FrameHub keeps hardware sensors disabled until you explicitly enable this module. This avoids unnecessary background RAM/CPU usage while the watcher remains active.",
        ["Hardware.Monitor.Title"] = "Hardware Monitor",
        ["Hardware.Monitor.On"] = "ON",
        ["Hardware.Monitor.Off"] = "OFF",
        ["Hardware.Monitor.DescriptionOn"] = "Telemetry is enabled. Sensors are opened only while this switch is active.",
        ["Hardware.Monitor.DescriptionOff"] = "Hardware sensors are not initialized. This keeps FrameHub lightweight in the background.",
        ["Hardware.Cpu"] = "CPU",
        ["Hardware.Gpu"] = "GPU",
        ["Hardware.GpuLoad"] = "GPU load",
        ["Hardware.Ram"] = "RAM",
        ["Hardware.Vram"] = "VRAM",
        ["Hardware.BackendMissing"] = "Backend not connected yet",
        ["Hardware.BackendActive"] = "Sensors active",
        ["Hardware.BackendInactive"] = "Sensors closed",
        ["Hardware.BackgroundBehavior.Title"] = "Background behavior",
        ["Hardware.ProfileWatcher.Title"] = "Profile watcher",
        ["Hardware.ProfileWatcher.Status"] = "Reserved as always-on module",
        ["Hardware.ProfileWatcher.StatusActive"] = "Active. Profile detection remains on in the background.",
        ["Hardware.ProfileWatcher.StatusInactive"] = "Inactive.",
        ["Hardware.StorageSensors.Title"] = "Storage sensors",
        ["Hardware.StorageSensors.Description"] = "Disabled by default. Optional later.",
        ["Hardware.RefreshModes.Title"] = "Refresh modes",
        ["Hardware.RefreshModes.Description"] = "Current mode uses the configured refresh interval. Hardware telemetry remains fully manual and separate from the background profile watcher.",

        ["Logs.Title"] = "Logs",
        ["Logs.Subtitle"] = "Runtime activity and diagnostics.",
        ["Logs.ActivityTitle"] = "Recent activity",
        ["Logs.OpenFolder"] = "Open log folder",
        ["Logs.Clear"] = "Clear activity",
    };

    private static readonly Dictionary<string, string> Polish = new(StringComparer.OrdinalIgnoreCase)
    {
        ["App.Tagline"] = "Otwarte centrum wydajności Windows dla gier i aplikacji",
        ["Language.Label"] = "Język",
        ["Language.English"] = "English",
        ["Language.Polish"] = "Polski",
        ["Status.CoreFoundation"] = "Fundament rdzenia",
        ["Status.WatcherFoundationReady"] = "Watcher gotowy",
        ["Status.CoreMigrated"] = "Rdzeń aktywny",
        ["Status.WatcherActive"] = "Watcher aktywny",
        ["Status.WatcherInactive"] = "Watcher nieaktywny",

        ["Nav.Dashboard"] = "Panel główny",
        ["Nav.Library"] = "Biblioteka",
        ["Nav.Session"] = "Optymalizacja sesji",
        ["Nav.CoreControl"] = "Kontrola rdzeni",
        ["Nav.ProfilesRules"] = "Profile i reguły",
        ["Nav.Background"] = "Aplikacje w tle",
        ["Nav.Toolkit"] = "Narzędzia systemowe",
        ["Nav.Hardware"] = "Sprzęt",
        ["Nav.Benchmark"] = "Benchmarki",
        ["Nav.WindowsTuning"] = "Strojenie Windows",
        ["Nav.Settings"] = "Ustawienia",
        ["Nav.Logs"] = "Logi",
        ["Nav.Games"] = "Gry",
        ["Nav.Boost"] = "Boost",
        ["Nav.Processes"] = "Procesy",
        ["Nav.Profiles"] = "Profile",
        ["Nav.Tweaks"] = "Tweaki",
        ["Nav.Debloat"] = "Windows 11 Debloat",

        ["Badge.Soon"] = "WKRÓTCE",
        ["Badge.Safe"] = "SAFE",
        ["Badge.Planned"] = "PLAN",
        ["Badge.Preview"] = "PODGLĄD",
        ["Badge.Ready"] = "GOTOWE",

        ["Dashboard.Title"] = "Panel główny",
        ["Dashboard.Subtitle"] = "Mapa produktu FrameHub, status aktywnego rdzenia i kolejne moduły.",
        ["Metric.BackgroundWatcher.Title"] = "Watcher w tle",
        ["Metric.BackgroundWatcher.Value"] = "Zarezerwowany",
        ["Metric.BackgroundWatcher.ValueActive"] = "Aktywny",
        ["Metric.BackgroundWatcher.ValueOff"] = "Wyłączony",
        ["Metric.BackgroundWatcher.Detail"] = "{0} aktywnych profili",
        ["Metric.OptimizedApps.Title"] = "Optymalizowane aplikacje",
        ["Metric.OptimizedApps.Value"] = "0",
        ["Metric.OptimizedApps.Detail"] = "Brak aktywnej sesji",
        ["Metric.HardwareMonitor.Title"] = "Monitor sprzętu",
        ["Metric.HardwareMonitor.Value"] = "Wyłączony",
        ["Metric.HardwareMonitor.Detail"] = "Ręczny moduł telemetrii",
        ["Metric.Debloat.Title"] = "Strojenie Windows",
        ["Metric.Debloat.Value"] = "Podgląd",
        ["Metric.Debloat.Detail"] = "Brak zmian systemowych",
        ["Dashboard.FoundationPlan.Title"] = "Mapa produktu",
        ["Dashboard.FoundationPlan.Description"] = "FrameHub to open-source'owe centrum wydajności przygotowane pod sesje gamingowe, reguły aplikacji, narzędzia systemowe i bezpieczne strojenie Windows. Planowane moduły będą dodawane etapami z jasnym opisem oraz cofaniem zmian tam, gdzie to potrzebne.",
        ["Dashboard.Target.Title"] = "Obecny fundament",
        ["Dashboard.Target.Description"] = "Kontrola rdzeni jest już podłączona: profile procesów, CPU Sets, affinity, priorytet, logowanie i watcher profili w tle.",
        ["Dashboard.Migration.Title"] = "Kolejne moduły",
        ["Dashboard.Migration.Description"] = "Biblioteka, Optymalizacja sesji, Aplikacje w tle, Narzędzia systemowe, Benchmarki i Strojenie Windows są rozpisane w UI i będą wdrażane etapami.",
        ["Dashboard.RecentActivity.Title"] = "Ostatnia aktywność",
        ["Activity.ShellInitialized"] = "Shell produktu FrameHub został zainicjalizowany.",
        ["Activity.WatcherReserved"] = "Watcher profili w tle jest aktywny i niezależny od UI.",
        ["Activity.HardwareDisabled"] = "Monitor sprzętu jest wyłączony do momentu ręcznego włączenia.",
        ["Activity.DebloatPlanned"] = "Strojenie Windows jest tylko podglądem. Żadne akcje debloat nie są włączone.",

        ["Placeholder.CurrentState.Title"] = "Obecny stan",
        ["Placeholder.CurrentState.Description"] = "Ten moduł ma już miejsce w nawigacji produktu. Funkcje będą podłączane bezpiecznymi, testowalnymi etapami zamiast dodawania ryzykownych zmian systemowych naraz.",
        ["Placeholder.PlannedCapabilities.Title"] = "Planowane możliwości",
        ["Placeholder.SafetyRule.Title"] = "Zasada bezpieczeństwa FrameHub",
        ["Placeholder.SafetyRule.Description"] = "Bez edycji pamięci gier, bez DLL injection, bez sterowników kernelowych, bez obchodzenia antycheatów i bez ukrytych destrukcyjnych tweaków. Każda globalna zmiana musi być jawna, odwracalna i zalogowana.",


        ["Library.Title"] = "Biblioteka",
        ["Library.Subtitle"] = "Wykryte i ręcznie dodane gry, aplikacje oraz narzędzia w tle.",
        ["Library.ScanTitle"] = "Skanuj biblioteki gier",
        ["Library.ManualTitle"] = "Dodaj ręcznie",
        ["Library.ItemsTitle"] = "Elementy biblioteki",
        ["Library.CustomFoldersTitle"] = "Własne lokalizacje bibliotek",
        ["Library.Empty"] = "Przeskanuj Steam/Epic, dodaj własny folder albo wskaż plik .exe ręcznie.",
        ["Library.DisplayName"] = "Nazwa wyświetlana",
        ["Library.Executable"] = "Ścieżka do pliku EXE",
        ["Library.Type"] = "Typ",
        ["Library.Browse"] = "Wybierz",
        ["Library.AddManual"] = "Dodaj",
        ["Library.ScanSteam"] = "Skanuj Steam",
        ["Library.ScanEpic"] = "Skanuj Epic",
        ["Library.ScanAll"] = "Skanuj wszystko",
        ["Library.AddFolder"] = "Dodaj folder",
        ["Library.ScanCustom"] = "Skanuj własne foldery",
        ["Library.RefreshStatus"] = "Odśwież status",
        ["Library.SafetyTitle"] = "Tylko bezpieczne wykrywanie",
        ["Library.SafetyDescription"] = "Biblioteka tylko odczytuje manifesty launcherów i wskazane foldery. Nie modyfikuje gier, nie wstrzykuje plików, nie czyta pamięci gry i nie dotyka procesów antycheata.",
        ["Library.Remove"] = "Usuń",
        ["Library.Ready"] = "Biblioteka gotowa.",
        ["Library.ReadyCount"] = "{0}/{1} gotowe",
        ["Library.NotConfigured"] = "Nie skonfigurowano",
        ["Library.ExeMissing"] = "Nie wybrano pliku EXE",
        ["Library.ExecutableMissing"] = "Najpierw wybierz istniejący plik .exe.",
        ["Library.WatcherOn"] = "Watcher włączony",
        ["Library.WatcherOff"] = "Watcher wyłączony",
        ["Library.ProfileLinked"] = "Profil powiązany",
        ["Library.ProfileMissing"] = "Brak profilu",
        ["Library.Status.Optimized"] = "Działa + profil",
        ["Library.Status.Running"] = "Działa",
        ["Library.Status.NotRunning"] = "Nie działa",
        ["Library.Status.Ready"] = "Gotowe",
        ["Library.Status.NeedsSetup"] = "Wymaga konfiguracji",
        ["Library.ManualAdded"] = "Dodano element ręczny.",
        ["Library.ScanResult"] = "Wykryto {0} elementów.",
        ["Library.SourceScanResult"] = "Skan {0} wykrył {1} elementów.",
        ["Library.FolderAdded"] = "Dodano folder: {0}",
        ["Library.ItemRemoved"] = "Usunięto: {0}",
        ["Library.Type.Game"] = "Gra",
        ["Library.Type.App"] = "Aplikacja",
        ["Library.Type.BackgroundApp"] = "Aplikacja w tle",
        ["Library.Type.Launcher"] = "Launcher",
        ["Library.DetailsTitle"] = "Wybrany element",
        ["Library.NoSelection"] = "Wybierz element biblioteki, aby zarządzać profilem lub ustawieniami gry.",
        ["Library.Launch"] = "Uruchom",
        ["Library.OpenFolder"] = "Otwórz folder",
        ["Library.ProfileEditorTitle"] = "Profil optymalizacji",
        ["Library.ProfileEditorHint"] = "Wybierz tryb, priorytet i dokładny przydział CPU dla tej gry/aplikacji.",
        ["Library.CpuCores"] = "Rdzenie",
        ["Library.CpuThreads"] = "Wątki SMT / HT",
        ["Library.CreateUpdateProfile"] = "Utwórz / zaktualizuj profil",
        ["Library.ApplyProfileNow"] = "Zastosuj profil teraz",
        ["Library.ProfileSaved"] = "Zapisano profil optymalizacji dla {0}.",
        ["Library.ProfileApplied"] = "Zastosowano profil dla {0}.",
        ["CS2.Title"] = "Optymalizacja Counter-Strike 2",
        ["CS2.Subtitle"] = "Analiza ustawień CS2, powiązanie profilu CPU oraz bezpieczne presety configu z backupem przed zmianami.",
        ["CS2.Scan"] = "Skanuj ustawienia CS2",
        ["CS2.Backup"] = "Utwórz backup",
        ["CS2.ApplyPreset"] = "Utwórz backup + zastosuj wybrane",
        ["CS2.RestoreLatest"] = "Pokaż ostatni backup",
        ["CS2.CurrentSettings"] = "Edytor ustawień CS2",
        ["CS2.Preset"] = "Preset",
        ["CS2.NotScanned"] = "Wybierz Counter-Strike 2 i przeskanuj ustawienia.",
        ["CS2.NotDetected"] = "Nie wykryto jeszcze configu video CS2.",

        ["CS2.OverviewTitle"] = "Wykryte ustawienia CS2",
        ["CS2.Card.Resolution"] = "Rozdzielczość",
        ["CS2.Card.DisplayMode"] = "Tryb wyświetlania",
        ["CS2.Card.VSync"] = "Synchronizacja pionowa",
        ["CS2.Card.Baseline"] = "Zgodność z baseline",
        ["CS2.ConfigPath"] = "Plik configu",
        ["CS2.NotScannedShort"] = "Nie skanowano",
        ["CS2.BaselineMatch"] = "{0}/{1} zgodnych",
        ["CS2.PresetDescriptionFallback"] = "Wybierz preset, aby porównać aktualne ustawienia CS2 z baseline FrameHub.",
        ["CS2.Preset.cs2_latest_backup.Description"] = "Wartości wczytane z ostatniego backupu CS2 utworzonego przez FrameHub. Użyj tego do porównania lub przywrócenia pojedynczych ustawień.",
        ["CS2.Preset.cs2_current_backup_placeholder.Description"] = "Nie znaleziono wcześniejszego backupu CS2. Ten preset odzwierciedla obecnie wykryty config.",
        ["CS2.Preset.cs2_competitive_baseline.Description"] = "Competitive Baseline FrameHub oparty na Twoich ustawieniach CS2. Zachowuje te same wartości competitive i zmienia tylko tryb wyświetlania na prawdziwy pełny ekran.",
        ["CS2.Table.Apply"] = "Zastosuj",
        ["CS2.Table.Setting"] = "Ustawienie",
        ["CS2.Table.Current"] = "Aktualnie",
        ["CS2.Table.Recommended"] = "Polecane",
        ["CS2.Table.SetTo"] = "Ustaw",
        ["CS2.Table.Status"] = "Status",
        ["CS2.ApplyThisSetting"] = "Zastosuj to ustawienie",
        ["CS2.ReadOnlySetting"] = "Tylko informacyjnie",
        ["CS2.SafetyTitle"] = "Model bezpieczeństwa CS2 w FrameHub",
        ["CS2.SafetyDescription"] = "FrameHub czyta pliki configu CS2, tworzy backupy i stosuje wyłącznie wybrane tekstowe zmiany w configu. Zamknij CS2 przed zastosowaniem zmian, inaczej gra może nadpisać config przy wyjściu.",
        ["CS2.SettingsListTitle"] = "Edytowalne ustawienia obrazu CS2",
        ["CS2.SettingsListHint"] = "Każda opcja jest pokazana jako normalne ustawienie z gry. Wybierz wartość z listy rozwijanej i zaznacz tylko zmiany, które chcesz zastosować.",
        ["CS2.Autoexec.Title"] = "Edytor CS2 autoexec.cfg",
        ["CS2.Autoexec.Subtitle"] = "Edytuj albo utwórz autoexec.cfg bezpośrednio z FrameHub. Dodawaj bezpieczne snippet'y: bindy granatów, duży radar i fps_max, a potem zapisz plik.",
        ["CS2.Autoexec.Path"] = "Ścieżka autoexec.cfg",
        ["CS2.Autoexec.NotDetected"] = "Nie wykryto folderu cfg gry CS2.",
        ["CS2.Autoexec.OpenCreate"] = "Otwórz / utwórz autoexec",
        ["CS2.Autoexec.Save"] = "Zapisz autoexec.cfg",
        ["CS2.Autoexec.OpenFolder"] = "Otwórz folder cfg",
        ["CS2.Autoexec.AddGrenades"] = "Dodaj bindy granatów",
        ["CS2.Autoexec.AddRadar"] = "Dodaj duży radar",
        ["CS2.Autoexec.AddFps"] = "Dodaj fps_max",
        ["CS2.Autoexec.FpsLabel"] = "FPS max",
        ["CS2.Autoexec.SnippetAdded"] = "Snippet dodany w edytorze autoexec. Zapisz plik, żeby zastosować zmianę.",
        ["CS2.Status.MatchesBaseline"] = "Zgodne z baseline",
        ["CS2.Status.DifferentFromBaseline"] = "Różni się",
        ["CS2.Status.OptionalPreference"] = "Opcjonalne / preferencja",
        ["CS2.Status.NotDetected"] = "Nie wykryto",
        ["CS2.Status.ReadOnly"] = "Tylko info",
        ["CS2.Value.NotDetected"] = "Nie wykryto automatycznie",
        ["CS2.Value.On"] = "Włączony",
        ["CS2.Value.Off"] = "Wyłączony",
        ["CS2.Value.Enabled"] = "Włączone",
        ["CS2.Value.Disabled"] = "Wyłączone",
        ["CS2.Value.Display.fullscreen"] = "Pełny ekran",
        ["CS2.Value.Display.borderless"] = "Pełny ekran bez obramowania",
        ["CS2.Value.Display.windowed"] = "Okno",
        ["CS2.Value.Display.not found"] = "Nie wykryto",
        ["CS2.Value.MSAA.Mode.none"] = "Żaden",
        ["CS2.Value.MSAA.Mode.cmaa2"] = "CMAA2",
        ["CS2.Value.MSAA.Mode.2x"] = "2X MSAA",
        ["CS2.Value.MSAA.Mode.4x"] = "4X MSAA",
        ["CS2.Value.MSAA.Mode.8x"] = "8X MSAA",
        ["CS2.Value.Quality.0"] = "Niskie",
        ["CS2.Value.Quality.1"] = "Średnie",
        ["CS2.Value.Quality.2"] = "Wysokie",
        ["CS2.Value.Quality.3"] = "Bardzo wysokie",
        ["CS2.Value.DynamicShadows.0"] = "Tylko słońce / ograniczone",
        ["CS2.Value.DynamicShadows.1"] = "Wszystkie",
        ["CS2.Value.TextureFiltering.0"] = "Dwuliniowe",
        ["CS2.Value.TextureFiltering.1"] = "Trójliniowe",
        ["CS2.Value.TextureFiltering.2"] = "Anizotropowe 2X",
        ["CS2.Value.TextureFiltering.3"] = "Anizotropowe 4X",
        ["CS2.Value.TextureFiltering.4"] = "Anizotropowe 8X",
        ["CS2.Value.TextureFiltering.5"] = "Anizotropowe 16X",
        ["CS2.Value.HDR.-1"] = "Jakość",
        ["CS2.Value.HDR.0"] = "Wydajność",
        ["CS2.Value.HDR.1"] = "Jakość",
        ["CS2.Value.FSR.0"] = "Wyłączone (Najwyższa jakość)",
        ["CS2.Value.FSR.1"] = "Jakość",
        ["CS2.Value.FSR.2"] = "Zbalansowane",
        ["CS2.Value.FSR.3"] = "Wydajność",
        ["CS2.Value.FSR.4"] = "Wydajność ultra",
        ["CS2.Value.Resolution.1280x1024"] = "1280x1024 (5:4; CS2 pokazuje jako 4:3)",
        ["CS2.Setting.cs2.resolution"] = "Rozdzielczość",
        ["CS2.Setting.cs2.display_mode"] = "Tryb wyświetlania",
        ["CS2.Setting.r_player_visibility_mode"] = "Zwiększ kontrast graczy",
        ["CS2.Setting.setting.mat_vsync"] = "Synchronizacja Pionowa",
        ["CS2.Setting.setting.r_low_latency"] = "AMD Anti-Lag 2.0 / Low Latency",
        ["CS2.Setting.cs2.msaa_mode"] = "Tryb antyaliasingu (multisampling)",
        ["CS2.Setting.setting.videocfg_shadow_quality"] = "Ogólna jakość cieni",
        ["CS2.Setting.setting.videocfg_dynamic_shadows"] = "Dynamiczne cienie",
        ["CS2.Setting.setting.videocfg_texture_detail"] = "Szczegóły modeli / tekstur",
        ["CS2.Setting.setting.r_texturefilteringquality"] = "Tryb filtrowania tekstur",
        ["CS2.Setting.setting.shaderquality"] = "Detale shadera",
        ["CS2.Setting.setting.videocfg_particle_detail"] = "Szczegóły cząsteczek",
        ["CS2.Setting.setting.videocfg_ao_detail"] = "Okluzja otoczenia",
        ["CS2.Setting.setting.videocfg_hdr_detail"] = "High Dynamic Range",
        ["CS2.Setting.setting.videocfg_fsr_detail"] = "FidelityFX Super Resolution",
        ["CS2.Description.cs2.resolution"] = "Najczęściej używane rozdzielczości competitive. 1280x960 i 1440x1080 to opcje 4:3.",
        ["CS2.Description.cs2.display_mode"] = "Pełny ekran jest rekomendowany pod wydajność; borderless to wygodna preferencja.",
        ["CS2.Description.r_player_visibility_mode"] = "Poprawia kontrast i widoczność modeli graczy.",
        ["CS2.Description.setting.mat_vsync"] = "V-Sync powinien zostać wyłączony dla niższego input laga.",
        ["CS2.Description.setting.r_low_latency"] = "Opcja niskiego opóźnienia udostępniona przez CS2 / sterownik.",
        ["CS2.Description.cs2.msaa_mode"] = "Antyaliasing wygładza krawędzie, ale może obniżać FPS.",
        ["CS2.Description.setting.videocfg_shadow_quality"] = "Niższa jakość cieni zwykle poprawia FPS.",
        ["CS2.Description.setting.videocfg_dynamic_shadows"] = "Wszystkie dynamiczne cienie mogą pomagać w widoczności; ograniczone mogą być szybsze.",
        ["CS2.Description.setting.videocfg_texture_detail"] = "Niższe szczegóły modeli i tekstur zmniejszają obciążenie obrazu.",
        ["CS2.Description.setting.r_texturefilteringquality"] = "Filtrowanie tekstur wpływa na ostrość tekstur pod kątem.",
        ["CS2.Description.setting.shaderquality"] = "Niższe detale shadera zmniejszają obciążenie GPU.",
        ["CS2.Description.setting.videocfg_particle_detail"] = "Niższe szczegóły cząsteczek ograniczają koszt efektów.",
        ["CS2.Description.setting.videocfg_ao_detail"] = "Okluzja otoczenia dodaje cieniowanie kontaktowe i kosztuje wydajność.",
        ["CS2.Description.setting.videocfg_hdr_detail"] = "Preferencja HDR: jakość albo wydajność.",
        ["CS2.Description.setting.videocfg_fsr_detail"] = "FSR może poprawić FPS kosztem ostrości obrazu.",

        ["Module.Library.Title"] = "Biblioteka",
        ["Module.Library.Subtitle"] = "Gry i profile aplikacji w jednym miejscu.",
        ["Module.Library.Status"] = "Planowane dla v0.2.0",
        ["Module.Library.Description"] = "Biblioteka zastąpi ręczne szukanie procesów czystymi kartami gier i aplikacji. Użytkownik przypisze ścieżkę EXE, ikonę, nazwy procesów i profil optymalizacji.",
        ["Module.Library.Item1"] = "Kreator ręcznego dodawania gry lub aplikacji",
        ["Module.Library.Item2"] = "Przypisanie do ścieżki EXE, nie tylko nazwy procesu",
        ["Module.Library.Item3"] = "Status działania per element: działa / nie działa",
        ["Module.Library.Item4"] = "Późniejsze skanery launcherów: Steam, Epic, GOG, Battle.net, Riot, EA i Ubisoft",
        ["Module.Library.Item5"] = "Typ profilu: gra, aplikacja, aplikacja tła albo launcher",

        ["Module.Session.Title"] = "Optymalizacja sesji",
        ["Module.Session.Subtitle"] = "Przejrzyste sesje gamingowe jednym kliknięciem.",
        ["Module.Session.Status"] = "Planowane dla v0.3.0",
        ["Module.Session.Description"] = "Optymalizacja sesji nie będzie magicznym przyciskiem FPS. Aplikacja pokaże dokładnie jakie akcje zostaną wykonane, czy wymagają administratora i co zostanie przywrócone po zamknięciu gry.",
        ["Module.Session.Item1"] = "Zastosowanie wybranego profilu gry lub aplikacji",
        ["Module.Session.Item2"] = "Opcjonalny plan zasilania Wysoka wydajność podczas sesji",
        ["Module.Session.Item3"] = "Opcjonalne reguły aplikacji w tle",
        ["Module.Session.Item4"] = "Log przywracania zmian globalnych po sesji",
        ["Module.Session.Item5"] = "Etykiety akcji: Safe / Advanced / Experimental",

        ["Module.Background.Title"] = "Aplikacje w tle",
        ["Module.Background.Subtitle"] = "Reguły dla aplikacji działających podczas gry.",
        ["Module.Background.Status"] = "Planowane po Optymalizacji sesji",
        ["Module.Background.Description"] = "Ten moduł będzie zarządzał przeglądarkami, launcherami, Discordem, RGB i updaterami bez ślepego zabijania procesów systemowych. Domyślne zachowanie będzie ostrożne i odwracalne.",
        ["Module.Background.Item1"] = "Obniżenie priorytetu wybranych aplikacji tła",
        ["Module.Background.Item2"] = "Przeniesienie wybranych aplikacji na rdzenie tła",
        ["Module.Background.Item3"] = "Memory Relief z jasnym ostrzeżeniem i denylistą",
        ["Module.Background.Item4"] = "Pytanie przed zamknięciem wybranych aplikacji",
        ["Module.Background.Item5"] = "Eksperymentalne wstrzymanie tylko z mocnymi ostrzeżeniami",

        ["Module.Toolkit.Title"] = "Narzędzia systemowe",
        ["Module.Toolkit.Subtitle"] = "Małe narzędzia Windows, nie magiczne ryzykowne tweaki.",
        ["Module.Toolkit.Status"] = "Planowany moduł narzędziowy",
        ["Module.Toolkit.Description"] = "Narzędzia systemowe zbiorą bezpieczne funkcje codziennego użytku z podglądem, opisami i cofaniem zmian tam, gdzie to potrzebne.",
        ["Module.Toolkit.Item1"] = "Bezpieczne czyszczenie: TEMP, user TEMP, Kosz i shader cache z podglądem",
        ["Module.Toolkit.Item2"] = "Skróty do Menedżera zadań, Monitora zasobów i Autostartu",
        ["Module.Toolkit.Item3"] = "Narzędzia procesów z denylistą procesów krytycznych",
        ["Module.Toolkit.Item4"] = "Presety DNS: automatyczny, Cloudflare, Google, Quad9 i własny",
        ["Module.Toolkit.Item5"] = "Naprawa: SFC, DISM, Flush DNS i reset Winsock",
        ["Module.Toolkit.Item6"] = "Punkt przywracania i klasyczne menu kontekstowe Windows 11",

        ["Module.Benchmark.Title"] = "Benchmarki",
        ["Module.Benchmark.Subtitle"] = "FPS, frametime i raporty przed/po.",
        ["Module.Benchmark.Status"] = "Planowane po ustabilizowaniu core workflow",
        ["Module.Benchmark.Description"] = "Benchmarki mają sprawić, że FrameHub będzie mierzalny, a nie oparty o placebo. Celem jest prosty przepływ przed/po, eksport CSV i czytelne statystyki.",
        ["Module.Benchmark.Item1"] = "Średni FPS i podgląd frametime",
        ["Module.Benchmark.Item2"] = "1% low i 0.1% low",
        ["Module.Benchmark.Item3"] = "Raport przed / po optymalizacji",
        ["Module.Benchmark.Item4"] = "Możliwa integracja z PresentMon później",

        ["Module.WindowsTuning.Title"] = "Strojenie Windows",
        ["Module.WindowsTuning.Subtitle"] = "Plan bezpiecznego strojenia Windows 11 w trybie podglądu.",
        ["Module.WindowsTuning.Status"] = "Tylko podgląd",
        ["Module.WindowsTuning.Description"] = "To zastępuje stary pomysł debloat jednym kliknięciem. FrameHub pokaże strojenie Windows dopiero z podglądem, punktem przywracania, backupem i cofaniem. Nie będzie domyślnie wyłączać usług bezpieczeństwa.",
        ["Module.WindowsTuning.Item1"] = "Podgląd zmian przed zastosowaniem",
        ["Module.WindowsTuning.Item2"] = "Punkt przywracania przed ryzykownymi akcjami",
        ["Module.WindowsTuning.Item3"] = "Backup rejestru i plan rollbacku",
        ["Module.WindowsTuning.Item4"] = "Grupy: prywatność, zadania w tle, autostart i Explorer UX",
        ["Module.WindowsTuning.Item5"] = "Bez domyślnego wyłączania Defendera, Integralności pamięci i antycheatów",

        ["Module.Settings.Title"] = "Ustawienia",
        ["Module.Settings.Subtitle"] = "Konfiguracja aplikacji.",
        ["Module.Settings.Status"] = "Fundament",
        ["Module.Settings.Description"] = "Ustawienia będą zarządzać autostartem, trayem, motywem, językiem, logami, aktualizacjami i domyślnymi zasadami bezpieczeństwa.",
        ["Module.Settings.Item1"] = "Start z Windows",
        ["Module.Settings.Item2"] = "Minimalizacja / zamknięcie do traya",
        ["Module.Settings.Item3"] = "Motyw i język",
        ["Module.Settings.Item4"] = "Logowanie i diagnostyka",
        ["Module.Settings.Item5"] = "Sprawdzanie aktualizacji i domyślne zasady bezpieczeństwa",

        ["Module.Logs.Title"] = "Logi",
        ["Module.Logs.Subtitle"] = "Diagnostyka i log aktywności.",
        ["Module.Logs.Status"] = "Gotowe",
        ["Module.Logs.Description"] = "Logi pokazują aktywność watchera, zastosowane profile, nieudane akcje i przyszłe podsumowania sesji.",
        ["Module.Logs.Item1"] = "Ostatnia aktywność",
        ["Module.Logs.Item2"] = "Otwórz folder logów",
        ["Module.Logs.Item3"] = "Kopiuj diagnostykę później",
        ["Module.Logs.Item4"] = "Wyczyść aktywność UI",


        ["Settings.Title"] = "Ustawienia",
        ["Settings.Subtitle"] = "Autostart, tray, język, logi, aktualizacje i bezpieczne domyślne opcje.",
        ["Settings.StartupTitle"] = "Uruchamianie",
        ["Settings.BehaviorTitle"] = "Okno i zasobnik systemowy",
        ["Settings.LoggingTitle"] = "Logowanie i aktualizacje",
        ["Settings.SafetyTitle"] = "Bezpieczeństwo i opcje zaawansowane",
        ["Settings.DiagnosticsTitle"] = "Interwały odświeżania i diagnostyka",
        ["Settings.LanguageTitle"] = "Język aplikacji",
        ["Settings.StartWithWindows"] = "Uruchamiaj z systemem Windows",
        ["Settings.RunAsAdmin"] = "Uruchamiaj jako administrator",
        ["Settings.StartMinimized"] = "Uruchom zminimalizowany",
        ["Settings.MinimizeToTray"] = "Minimalizuj do zasobnika",
        ["Settings.CloseToTray"] = "Zamykaj do zasobnika",
        ["Settings.LogEnabled"] = "Włącz logowanie do pliku",
        ["Settings.CheckUpdates"] = "Sprawdzaj aktualizacje przy starcie",
        ["Settings.AllowRealtime"] = "Pokaż priorytet RealTime (zaawansowane)",
        ["Settings.StorageSensors"] = "Włącz czujniki dysków w monitorze sprzętu",
        ["Settings.ProcessRefresh"] = "Odświeżanie listy procesów (sekundy)",
        ["Settings.WatcherRefresh"] = "Interwał watchera w tle (sekundy)",
        ["Settings.HardwareRefresh"] = "Odświeżanie sprzętu (sekundy)",
        ["Settings.RestartAsAdminButton"] = "Uruchom jako admin",
        ["Settings.CheckUpdatesButton"] = "Sprawdź teraz",
        ["Settings.OpenAppData"] = "Otwórz folder AppData",
        ["Settings.OpenLogs"] = "Otwórz folder logów",
        ["Settings.AdminYes"] = "Admin: tak",
        ["Settings.AdminNo"] = "Admin: nie",
        ["Settings.Saved"] = "Ustawienia zapisane",
        ["Settings.CheckingUpdates"] = "Sprawdzanie aktualizacji...",
        ["Settings.UpdateFailed"] = "Sprawdzanie aktualizacji nie powiodło się:",
        ["Settings.UpdateAvailable"] = "Dostępna aktualizacja: v{0}",
        ["Settings.OpenReleaseQuestion"] = "Otworzyć stronę wydania?",
        ["Settings.UpToDate"] = "FrameHub jest aktualny.",

        ["Processes.Title"] = "Kontrola rdzeni",
        ["Processes.Subtitle"] = "CPU Sets, affinity, priorytet i zapisywanie profili dla uruchomionych procesów.",
        ["Processes.ListTitle"] = "Uruchomione procesy",
        ["Processes.CoreSelectionTitle"] = "Wybór rdzeni CPU",
        ["Processes.SettingsTitle"] = "Ustawienia optymalizacji",
        ["Processes.SettingsSubtitle"] = "Wybierz proces, rdzenie i zapisz profil do ponownego użycia.",
        ["Processes.Priority"] = "Priorytet",
        ["Processes.Mode"] = "Tryb optymalizacji",
        ["Processes.Apply"] = "Zastosuj teraz",
        ["Processes.SaveProfile"] = "Zapisz profil",
        ["Processes.SelectAll"] = "Zaznacz wszystko",
        ["Processes.ClearAll"] = "Odznacz wszystko",
        ["Processes.DisableSmt"] = "Wyłącz SMT/HT",
        ["Processes.DisableECores"] = "Wyłącz E-core",
        ["Processes.Name"] = "Nazwa",
        ["Processes.Instances"] = "Inst.",
        ["Processes.Ram"] = "RAM",
        ["Processes.Cpu"] = "CPU",
        ["Processes.NoSelection"] = "Wybierz proces, aby skonfigurować optymalizację.",
        ["Processes.Selected"] = "Wybrano: {0}",

        ["Profiles.Title"] = "Profile i reguły",
        ["Profiles.Subtitle"] = "Zapisane reguły procesów pilnowane w tle.",
        ["Profiles.SavedTitle"] = "Zapisane profile",
        ["Profiles.DetailsTitle"] = "Szczegóły profilu",
        ["Profiles.Apply"] = "Zastosuj teraz",
        ["Profiles.Delete"] = "Usuń",
        ["Profiles.Empty"] = "Nie wybrano profilu.",
        ["Profiles.Name"] = "Nazwa",
        ["Profiles.Mode"] = "Tryb",
        ["Profiles.Priority"] = "Priorytet",
        ["Profiles.Enabled"] = "Aktywny",

        ["Hardware.Title"] = "Monitor sprzętu",
        ["Hardware.Subtitle"] = "Ręczny moduł telemetrii. Sensory pozostają zamknięte, dopóki ich nie włączysz.",
        ["Hardware.Telemetry.Title"] = "Ręczna telemetria sprzętu",
        ["Hardware.Telemetry.Description"] = "FrameHub trzyma sensory sprzętowe wyłączone, dopóki wyraźnie nie włączysz tego modułu. Dzięki temu aplikacja nie zużywa niepotrzebnie RAM/CPU w tle, a watcher nadal działa.",
        ["Hardware.Monitor.Title"] = "Monitor sprzętu",
        ["Hardware.Monitor.On"] = "ON",
        ["Hardware.Monitor.Off"] = "OFF",
        ["Hardware.Monitor.DescriptionOn"] = "Telemetria jest włączona. Sensory są otwierane tylko wtedy, gdy ten przełącznik jest aktywny.",
        ["Hardware.Monitor.DescriptionOff"] = "Sensory sprzętowe nie są inicjalizowane. Dzięki temu FrameHub pozostaje lekki w tle.",
        ["Hardware.Cpu"] = "CPU",
        ["Hardware.Gpu"] = "GPU",
        ["Hardware.GpuLoad"] = "Użycie GPU",
        ["Hardware.Ram"] = "RAM",
        ["Hardware.Vram"] = "VRAM",
        ["Hardware.BackendMissing"] = "Backend nie jest jeszcze podłączony",
        ["Hardware.BackendActive"] = "Sensory aktywne",
        ["Hardware.BackendInactive"] = "Sensory zamknięte",
        ["Hardware.BackgroundBehavior.Title"] = "Zachowanie w tle",
        ["Hardware.ProfileWatcher.Title"] = "Watcher profili",
        ["Hardware.ProfileWatcher.Status"] = "Zarezerwowany jako moduł zawsze aktywny",
        ["Hardware.ProfileWatcher.StatusActive"] = "Aktywny. Wykrywanie profili działa w tle.",
        ["Hardware.ProfileWatcher.StatusInactive"] = "Nieaktywny.",
        ["Hardware.StorageSensors.Title"] = "Sensory dysków",
        ["Hardware.StorageSensors.Description"] = "Domyślnie wyłączone. Opcjonalnie później.",
        ["Hardware.RefreshModes.Title"] = "Tryby odświeżania",
        ["Hardware.RefreshModes.Description"] = "Obecny tryb używa skonfigurowanego interwału odświeżania. Telemetria sprzętowa pozostaje ręczna i oddzielona od watchera profili w tle.",

        ["Logs.Title"] = "Logi",
        ["Logs.Subtitle"] = "Aktywność runtime i diagnostyka.",
        ["Logs.ActivityTitle"] = "Ostatnia aktywność",
        ["Logs.OpenFolder"] = "Otwórz folder logów",
        ["Logs.Clear"] = "Wyczyść aktywność",
    };
}
